package com.tddworks.openai.api.images.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents the url or the content of an image generated by the OpenAI API.
 * @see [Image](https://beta.openai.com/docs/api-reference/images/create)
 */
@Serializable
data class Image(

    /**
     * The URL of the generated image, if response_format is url (default).
     */
    @SerialName("url")
    val url: String? = null,

    /**
     * The base64-encoded JSON of the generated image, if response_format is b64_json.
     */
    @SerialName("b64_json")
    val b64JSON: String? = null,

    /**
     *The prompt that was used to generate the image, if there was any revision to the prompt.
     */
    @SerialName("revised_prompt")
    val revisedPrompt: String? = null,
)
